# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admins:
            memory:
                users:
                    admin:
                        password: "foobar"
                        roles: [ROLE_ADMIN]
        customers:
            id: security.customers_provider

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Models\Customer: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: admins
            http_basic:
                realm: "Admin area"

        main:
            anonymous: ~
            provider: customers
            form_login:
                login_path: public.sign_in
                check_path: public.sign_in
            logout:
                path: /signout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    access_control:
      -
          path: ^/admin
          roles: ROLE_ADMIN
      -
          path: ^/reserve
          roles: ROLE_USER
      -
          path: ^/signin,
          roles: IS_AUTHENTICATED_ANONYMOUSLY
