# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admins:
            memory:
                users:
                    admin:
                        password: "foobar"
                        roles: [ROLE_ADMIN]
        customers:
            id: security.customers_provider
        hosts:
            id: security.hosts_provider

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Models\Customer: plaintext
        AppBundle\Models\Host: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: admins
            http_basic:
                realm: "Admin area"

        host:
            anonymous: ~
            context: metinet
            pattern: ^/hosts
            provider: hosts
            form_login:
                login_path: public.host.sign_in
                check_path: public.host.sign_in
            logout:
                path: /signout
            access_denied_url: public.host.sign_in

        customer:
            pattern: ^/.*
            context: metinet
            anonymous: ~
            provider: customers
            form_login:
                login_path: public.customer.sign_in
                check_path: public.customer.sign_in
            logout:
                path: /signout
            access_denied_url: public.customer.sign_in

    role_hierarchy:
        ROLE_CUSTOMER: [ROLE_USER]
        ROLE_HOST: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER]

    access_control:
      -
          path: ^/admin
          roles: ROLE_ADMIN
      -
          path: ^/reserve
          roles: ROLE_CUSTOMER
      -
          path: ^/hosts/signup
          roles: IS_AUTHENTICATED_ANONYMOUSLY
      -
          path: ^/hosts/signin
          roles: IS_AUTHENTICATED_ANONYMOUSLY
      -
          path: ^/hosts
          roles: ROLE_HOST
      -
          path: ^/signin
          roles: IS_AUTHENTICATED_ANONYMOUSLY
